name: Bot Commands

on:
  issue_comment:
    types: [ created, edited ]

jobs:

  check_comment:
    runs-on: [ ubuntu-latest ]
    if: ${{ github.event.issue.pull_request }}
    outputs:
      request_build: ${{ steps.build_check.outputs.build }}
      do_checkout: ${{ steps.build_check.outputs.build }}
    steps:
      - id: build_check
        name: Check for build
        if: ${{ contains(github.event.comment.body, '/build') }}
        run: echo "::set-output name=build::true"

  checkout:
    runs-on: [ ubuntu-latest ] 
    needs: [ check_comment ]
    if: needs.check_comment.outputs.do_checkout == true
    steps:
      - uses: actions/checkout@v4

  trigger_build:
    name: Trigger build
    needs: [ check_comment, checkout ]
    if: needs.check_comment.outputs.request_build == true
    uses: ./.github/workflows/build.yml
    secrets: inherit
