name: Bot Commands

on:
  issue_comment:
    types: [ created, edited ]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
      JOB_CONTEXT: ${{ toJson(job) }}
      STEPS_CONTEXT: ${{ toJson(steps) }}
      RUNNER_CONTEXT: ${{ toJson(runner) }}
      STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      MATRIX_CONTEXT: ${{ toJson(matrix) }}
    steps:
      - name: Dump GitHub context
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        run: echo "$MATRIX_CONTEXT"
      - name: Create Summary
        run: |
          echo "# Dump Context" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## GITHUB_CONTEXT" >> $GITHUB_STEP_SUMMARY
          echo "$GITHUB_CONTEXT" >> $GITHUB_STEP_SUMMARY
          echo "## JOB_CONTEXT" >> $GITHUB_STEP_SUMMARY
          echo "$JOB_CONTEXT" >> $GITHUB_STEP_SUMMARY
          echo "## STEPS_CONTEXT" >> $GITHUB_STEP_SUMMARY
          echo "$STEPS_CONTEXT" >> $GITHUB_STEP_SUMMARY
          echo "## RUNNER_CONTEXT" >> $GITHUB_STEP_SUMMARY
          echo "$RUNNER_CONTEXT" >> $GITHUB_STEP_SUMMARY
          echo "## STRATEGY_CONTEXT" >> $GITHUB_STEP_SUMMARY
          echo "$STRATEGY_CONTEXT" >> $GITHUB_STEP_SUMMARY
          echo "## MATRIX_CONTEXT" >> $GITHUB_STEP_SUMMARY
          echo "$MATRIX_CONTEXT" >> $GITHUB_STEP_SUMMARY
         

  check_comment:
    runs-on: [ ubuntu-latest ]
    if: ${{ github.event.issue.pull_request }}
    outputs:
      request_build: ${{ steps.build_check.outputs.build }}
      request_run: ${{ steps.build_check.outputs.run }}
      do_checkout: ${{ steps.build_check.outputs.checkout  }}

    steps:
      - name: Print comment
        run: |
          echo "Processing: \"${{ github.event.comment.body }}\""
      - id: build_check
        name: Check for build
        if: contains(github.event.comment.body, '/build')
        run: |
          echo "Selected to BUILD"
          echo "build=true" >> $GITHUB_OUTPUT
          echo "checkout=true" >> $GITHUB_OUTPUT
      - id: run_check
        name: Check for run
        if: contains(github.event.comment.body, '/run')
        run: |
          echo "Selected to RUN"
          echo "run=true" >> $GITHUB_OUTPUT
          echo "checkout=true" >> $GITHUB_OUTPUT

  check_comment_request:
    runs-on: [ ubuntu-latest ] 
    needs: [ check_comment ]
    steps:
      - run: |
          echo "Check comment requests:"
          echo "do_checkout: ${{ needs.check_comment.outputs.do_checkout }}"
          echo "request_build: ${{ needs.check_comment.outputs.request_build }}"
          echo "request_run: ${{ needs.check_comment.outputs.request_run }}"

  checkout:
    runs-on: [ ubuntu-latest ] 
    needs: [ check_comment ]
    if:  needs.check_comment.outputs.do_checkout == 'true'
    steps:
      - uses: actions/checkout@v4

  trigger_build:
    name: Trigger build
    needs: [ check_comment, checkout ]
    if:  needs.check_comment.outputs.request_build == 'true'
    uses: ./.github/workflows/build.yml
    secrets: inherit

  trigger_run:
    name: Trigger run
    needs: [ check_comment, checkout ]
    if:  needs.check_comment.outputs.request_run == 'true'
    uses: ./.github/workflows/run.yml
    secrets: inherit
