name: Bot Commands

on:
  issue_comment:
    types: [ created, edited ]

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  check_comment:
    runs-on: [ ubuntu-latest ]
    if: ${{ github.event.issue.pull_request }}
    outputs:
      request_build: ${{ steps.build_check.outputs.build }}
      request_run: ${{ steps.build_check.outputs.run }}
      do_checkout: ${{ steps.build_check.outputs.checkout  }}

    steps:
      - id: build_check
        name: Check for build
        if: ${{ contains(github.event.comment.body, '/build') }}
        run: |
          echo "Selected to BUILD"
          echo "build=true" >> $GITHUB_OUTPUT
          echo "checkout=true" >> $GITHUB_OUTPUT
          gh api \
          --method POST \
          /repos/${{github.repository}}/pulls/comments/${{github.event.comment.id}}/reactions \
          -f content='+1'
      - id: run_check
        name: Check for run
        if: ${{ contains(github.event.comment.body, '/run') }}
        run: |
          echo "Selected to RUN"
          echo "run=true" >> $GITHUB_OUTPUT
          echo "checkout=true" >> $GITHUB_OUTPUT
          gh api \
          --method POST \
          /repos/${{github.repository}}/pulls/comments/${{github.event.comment.id}}/reactions \
          -f content='+1'

  checkout-debug:
    runs-on: [ ubuntu-latest ] 
    needs: [ check_comment ]
    steps:
      - run: |
          echo "Check 'needs.check_comment.outputs.do_checkout'"
          echo "do_checkout: ${{ needs.check_comment.outputs.do_checkout }}"

  checkout:
    runs-on: [ ubuntu-latest ] 
    needs: [ check_comment ]
    if:  ${{ needs.check_comment.outputs.do_checkout == 'true' }}
    steps:
      - uses: actions/checkout@v4

  trigger_build:
    name: Trigger build
    needs: [ check_comment, checkout ]
    if:  ${{ needs.check_comment.outputs.request_build == 'true' }}
    uses: ./.github/workflows/build.yml
    secrets: inherit

  trigger_run:
    name: Trigger run
    needs: [ check_comment, checkout ]
    if:  ${{ needs.check_comment.outputs.request_run == 'true' }}
    uses: ./.github/workflows/run.yml
    secrets: inherit
