name: Bot Commands

on:
  issue_comment:
    types: [ created, edited ]

jobs:

  check_comment:
    runs-on: [ ubuntu-latest ]
    if: ${{ github.event.issue.pull_request }}
    outputs:
      request_build: ${{ steps.build_check.outputs.build == 'true' }}
      request_run: ${{ steps.run_check.outputs.run == 'true' }}
      do_checkout: ${{ steps.build_check.outputs.build == 'true' || steps.run_check.outputs.run == 'true' }}
    steps:
      - id: build_check
        name: Check for build
        if: ${{ contains(github.event.comment.body, '/build') }}
        run: |
          echo "Selected to BUILD"
          echo "build=true" >> $GITHUB_OUTPUT
      - id: run_check
        name: Check for run
        if: ${{ contains(github.event.comment.body, '/run') }}
        run: |
          echo "Selected to RUN"
          echo "run=true" >> $GITHUB_OUTPUT

  comment-debug:
    runs-on: [ ubuntu-latest ] 
    needs: [ check_comment ]
    steps:
      - run: |
          echo "Check outputs"
          echo "do_checkout: ${{ needs.check_comment.outputs.do_checkout }}"
          echo "request_build: ${{ needs.check_comment.outputs.request_build }}"
          echo "request_run: ${{ needs.check_comment.outputs.request_run }}"
      - name: Print data
        run: |
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"

  checkout:
    runs-on: [ ubuntu-latest ] 
    needs: [ check_comment ]
    if:  ${{ needs.check_comment.outputs.do_checkout == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Print data
        run: |
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"

  trigger_build:
    name: Trigger build
    needs: [ check_comment, checkout ]
    if:  ${{ needs.check_comment.outputs.request_build == 'true' }}
    uses: ./.github/workflows/build.yml
    secrets: inherit

  trigger_run:
    name: Trigger run
    needs: [ check_comment, checkout ]
    if:  ${{ needs.check_comment.outputs.request_run == 'true' }}
    uses: ./.github/workflows/run.yml
    secrets: inherit
