name: Build

on:
  workflow_dispatch: # manual run
  pull_request:
  workflow_call: # called by other yml file

concurrency:
  # unique in PR or run_number in case of workflow_dispatch
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.job.job_id || github.run_number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Build Project
        run: |
          echo "Code Build!"
      - name: Comment
        run: |
          gh pr comment 1 --body "Hi from GitHub CLI"
