name: Build

on:
  workflow_dispatch: # manual run
  pull_request:
  workflow_call: # called by other yml file

concurrency:
  # unique in PR or run_number in case of workflow_dispatch
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_number }}
  cancel-in-progress: true

jobs:
  build:    
  name: Build
  runs-on: [ ubuntu-latest ]
  steps:
    run: |
        echo "Code Build!!!"