name: Run

on:
  workflow_dispatch: # manual run
  pull_request:
  workflow_call: # called by other yml file

concurrency:
  # unique in PR or run_number in case of workflow_dispatch
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.job.job_id || github.run_number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Run Project
        run: |
          echo "Run"
      - name: Print data
        run: |
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
